## Process Makefile.am with automake to create Makefile.in.
##
## Copyright (C) 1996 Free Software Foundation, Inc.
## This Makefile.am is free software; the Free Software Foundation
## gives unlimited permission to copy, distribute and modify it.
##
## Written by Gordon Matzigkeit <gord@gnu.ai.mit.edu>
AUTOMAKE_OPTIONS = gnits
SUBDIRS = doc libdld tests

include_HEADERS = ansidecl.h dld.h
noinst_HEADERS = system.h

EXTRA_DIST = .cvsignore dld.lsm
